language: objective-c
xcode_project: linphone.xcodeproj
xcode_scheme: linphone

git:
  submodules: false

env:
    global:
        - VERSION="8.1"
        - BYPASS_TOOLCHECK=1

install: 
    - cd submodules/build 
    - make download-sdk
    - cd ../..
    - git submodule update --init Classes/KIF
    - git submodule update --init --recursive submodules/linphone
    - ls -la

script:
    - xcodebuild -scheme linphone -project linphone.xcodeproj -sdk iphonesimulator${VERSION} -destination "platform=iOS Simulator,name=iPhone 6,OS=${VERSION}" test
